"""Dependency-light local mesh generation for OODrive asset requests."""

from __future__ import annotations

from pathlib import Path

from driverx.assets.types import AssetManifest, AssetRequest


def generate_local_procedural_assets(
    requests: list[AssetRequest],
    output_dir: Path,
) -> list[AssetManifest]:
    """Write small OBJ meshes for asset requests and return generated manifests."""

    mesh_dir = output_dir / "generated_assets"
    mesh_dir.mkdir(parents=True, exist_ok=True)
    manifests: list[AssetManifest] = []
    for request in requests:
        mesh_path = mesh_dir / f"{_safe_id(request.asset_id)}.obj"
        thumbnail_path = mesh_dir / f"{_safe_id(request.asset_id)}.ppm"
        mesh_path.write_text(_box_obj(request), encoding="utf-8")
        thumbnail_path.write_text(_ppm_thumbnail(request.semantic_tags), encoding="utf-8")
        manifests.append(
            AssetManifest.from_request(
                request,
                status="generated",
                provider="local_procedural",
                local_path=str(mesh_path),
                metadata={
                    "geometry_source": "local_procedural_box_mesh",
                    "mesh_format": "obj",
                    "thumbnail_path": str(thumbnail_path),
                    "quality_passes": True,
                    "custom_asset_imported_in_carla": False,
                },
            )
        )
    return manifests


def _box_obj(request: AssetRequest) -> str:
    length = max(0.1, float(request.dimensions_m.get("length", 1.0)))
    width = max(0.1, float(request.dimensions_m.get("width", 1.0)))
    height = max(0.1, float(request.dimensions_m.get("height", 0.5)))
    x = length / 2.0
    y = width / 2.0
    z = height
    name = _safe_id(request.asset_id)
    vertices = [
        (-x, -y, 0.0),
        (x, -y, 0.0),
        (x, y, 0.0),
        (-x, y, 0.0),
        (-x, -y, z),
        (x, -y, z),
        (x, y, z),
        (-x, y, z),
    ]
    faces = [
        (1, 2, 3, 4),
        (5, 8, 7, 6),
        (1, 5, 6, 2),
        (2, 6, 7, 3),
        (3, 7, 8, 4),
        (4, 8, 5, 1),
    ]
    lines = [
        f"# Generated by OODrive local_procedural provider for {request.asset_id}",
        f"o {name}",
    ]
    lines.extend(f"v {vx:.4f} {vy:.4f} {vz:.4f}" for vx, vy, vz in vertices)
    lines.extend("f " + " ".join(str(index) for index in face) for face in faces)
    return "\n".join(lines) + "\n"


def _ppm_thumbnail(tags: list[str]) -> str:
    tags_lower = {tag.lower() for tag in tags}
    if {"construction", "barrier"} & tags_lower:
        color = (230, 112, 38)
    elif {"roadside_vendor", "regional_context"} & tags_lower:
        color = (46, 130, 92)
    else:
        color = (82, 96, 120)
    pixels = " ".join(f"{color[0]} {color[1]} {color[2]}" for _ in range(64))
    return f"P3\n8 8\n255\n{pixels}\n"


def _safe_id(value: str) -> str:
    clean = "".join(ch if ch.isalnum() else "_" for ch in value.lower()).strip("_")
    return clean or "asset"


__all__ = ["generate_local_procedural_assets"]
